build:
    image: default-bionic

    environment:
        php:
            version: 8.3.0

    tests:
        override:
            - composer install --no-interaction
            -
                command: XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-clover=coverage.xml
                coverage:
                    file: coverage.xml
                    format: clover

filter:
    paths:
        - src/

checks:
    php:
        code_rating: true
        duplication: true
